<a href="https://colab.research.google.com/github/acorreia61201/SAOPythonPrimer/blob/main/Solutions5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SAO/LIP Python Primer Course Exercise Set 5

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/acorreia61201/SAOPythonPrimer/blob/main/exercises/Exercises5.ipynb)

## Exercise 1: Matrix Arithmetic

**Your task:** Solve the following matrix arithmetic problems using `numpy`, using the following definitions:

\begin{equation}
a = \begin{pmatrix}
4 \\ -2 \\ -7 \\
\end{pmatrix}, 
b = \begin{pmatrix}
-1 \\ 8 \\ 4 \\ 
\end{pmatrix}, 
c = \begin{pmatrix}
9 \\ 4 \\ -6 \\
\end{pmatrix}
\end{equation}

\begin{equation}
D = \begin{pmatrix}
5 & -3 & 2 \\
4 & 1 & 9 \\
\end{pmatrix}, 
E = \begin{pmatrix}
7 & 3 & 8 \\
-1 & 8 & 5 \\
6 & 9 & -2 \\
\end{pmatrix}, 
F = \begin{pmatrix}
0 & 4 \\
5 & -8 \\
8 & 7 \\
\end{pmatrix}
\end{equation}

- $a + b - c$

In [16]:
import numpy as np

# define all the matrices here
a = np.array([4, -2, -7])
b = np.array([-1, 8, 4])
c = np.array([9, 4, -6])
D = np.array([[5, -3, 2], [4, 1, 9]])
E = np.array([[7, 3, 8], [-1, 8, 5], [6, 9, -2]])
F = np.array([[0, 4], [5, -8], [8, 7]])

a + b - c

array([-6,  2,  3])

- $2a - 7b$

In [17]:
2*a - 7*b

array([ 15, -60, -42])

- $a \cdot c$

In [18]:
np.dot(a.reshape(1, 3), c.reshape(3, 1))
# if you use 2D arrays, they have to be a row and column vector. If you use 1D arrays, numpy will automatically do the conversion

array([[70]])

- $a \times b$

In [22]:
np.cross(a.reshape(1, 3), b.reshape(1, 3))
# if you use 2D arrays, they have to have the same shape. If you use 1D arrays, numpy will automatically do the conversion

array([[48, -9, 30]])

- $Da$

In [23]:
np.matmul(D, a)

array([ 12, -49])

- $\frac{1}{2}EF$

In [24]:
0.5*np.matmul(E, F)

array([[ 39.5,  30. ],
       [ 40. , -16.5],
       [ 14.5, -31. ]])

- $b^TEc$ ($b^T$ is the transpose of $b$; we need this for the multiplication to be defined) (Hint: If you defined $b$ and $c$ as row vectors (i.e. 1D arrays using `np.array()`) you'd technically be transposing $c$. Either way, make sure $b$ is a row vector and $c$ is a column vector, )

In [25]:
term1 = np.matmul(b, E) # multiply the first two factors first
np.matmul(term1, c.reshape(3, 1)) # then the third
# note that the original problem wouldn't work since b.T*F would give a 1x2 matrix

array([325])

## Exercise 2: Verifying Matrix Identities

We can use arrays to verify some important matrix identites used thoughout linear algebra.

**Your task:** For each identity, write a function that takes in some amount of arrays as inputs and evaluates any relevant values. Return the truth value of each identity (that is, return `True` if the identity is satisfied and `False` if it isn't). Try it out with some test matrices; feel free to use the ones above or define your own.

- The distributive property: $A(B + C) = AB + AC$

In [ ]:
# generating matrices; these are identities, so anything will work
A = E
B = E.T * 0.451
C = 3*B - 5*A/3.7

def dist(A, B, C):
    lhs = np.matmul(A, (B+C)) # left-hand side
    rhs = np.matmul(A, B) + np.matmul(A, C) # right-hand side
    return np.isclose(lhs, rhs) # are they equal? (element-wise)

dist(A, B, C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- The associative property (or lack thereof): $AB \neq BA$

In [ ]:
def assoc(A, B):
    lhs = np.matmul(A, B) # left-hand side
    rhs = np.matmul(B, A) # right-hand side
    return np.isclose(lhs, rhs) # are they equal?

assoc(A, B)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

- Sum of transposes: $A^T + B^T = (A + B)^T$

In [ ]:
def sumT(A, B):
    lhs = A.T + B.T # left-hand side
    rhs = (A + B).T # right-hand side
    return np.isclose(lhs, rhs) # are they equal?

sumT(A, B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- Product of transposes: $(ABC)^T = C^TB^TA^T$

In [ ]:
def mulT(A, B, C):
    lhs = np.matmul(np.matmul(A, B), C).T # left-hand side
    rhs = np.matmul(np.matmul(C.T, B.T), A.T) # right-hand side
    return np.isclose(lhs, rhs) # are they equal?

mulT(A, B, C)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- The identity matrix $I$: $AI = A$

In [ ]:
def iden(A):
    lhs = np.matmul(A, np.eye(np.shape(A)[0])) # left-hand side (shape[0] gives the num of rows)
    rhs = A # right-hand side
    return np.isclose(lhs, rhs)

iden(B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

- The trace of a matrix: $tr(A) = \sum_i{A_{ii}}$. $A_{ij}$ is the element in row $i$ and column $j$ of matrix $A$. You may use `numpy.trace()` to evaluate the left-hand side of this identity.

In [ ]:
def tr(A):
    lhs = np.trace(A) # left hand side
    rhs = 0
    for i in range(np.shape(A)[0]): # iterate over n of an n by n matrix
        rhs += A[i, i] # add the diagonal elements
    return np.isclose(lhs, rhs) # are they equal?

tr(A)

True

## Exercise 3: Computing the Inverse of a Matrix

Taking the inverse of a nonzero number is a trivial task. However, as you may know, doing the same for a matrix takes a bit more work. We define the *matrix inverse* as follows, assuming $A$ is a 2x2 *square matrix* (i.e. the numbers of rows and columns in $A$ are equal):

\begin{equation}
A^{-1} = \frac{1}{det(A)} \begin{pmatrix} A_{11} & -A_{01} \\ -A_{10} & A_{00} \\ \end{pmatrix}
\end{equation}

We define a new quantity $det(A)$ as the *determinant* of $A$. For a 2D matrix, calculating its value is trivial:

\begin{equation}
det(A) = A_{00}A_{11} - A_{01}A_{10}
\end{equation}

**Your task:** Write a function that takes a 2x2 matrix as an input and returns its inverse. The above formulas only work for this type of matrix, so you may add some logic to return an error message if the input is not 2x2. Test your function by verifying the following identity, which defines the identity matrix:

\begin{equation}
A^{-1}A = AA^{-1} = I
\end{equation}

In [ ]:
def inv(A):
    det = A[0, 0]*A[1, 1] - A[0, 1]*A[1, 0] # evaluate the determinant
    # set up matrix factor element-wise
    inverse = np.empty((2, 2))
    inverse[0, 0] = A[1, 1]
    inverse[0, 1] = -A[0, 1]
    inverse[1, 0] = -A[1, 0]
    inverse[1, 1] = A[0, 0]
    return inverse/det

A = np.array([[1, 2], [3, 4]]) # an invertible matrix
Ainv = inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
# check the identity
np.matmul(A, Ainv)

array([[1., 0.],
       [0., 1.]])

In [ ]:
B = np.array([[8, 6], [4, 3]]) # a non-invertible matrix
inv(B)

<ipython-input-53-dc07ea2d60ba>:9: RuntimeWarning: divide by zero encountered in true_divide
  return inverse/det


array([[ inf, -inf],
       [-inf,  inf]])

If you tested the function above, you may have gotten some errors. If you did, don't fret; there's a reason for this. If not, try inputting the following matrix:

\begin{equation}
\begin{pmatrix}
8 & 6 \\
4 & 3 \\
\end{pmatrix}
\end{equation}

This isn't an error on your part (assuming you did the first task correctly). Not all matrices have well-defined inverses. You can see this from the definition above; if the determinant of the matrix is zero, the coefficient will be undefined and you'll encounter a divide by zero error.

**Your code:** Modify your function with an `if` statement that handles this exception. Print out an error message `"Matrix has no inverse"` when you reach this condition.

In [ ]:
def inv(A):
    # handle non-invertible matrices
    det = A[0, 0]*A[1, 1] - A[0, 1]*A[1, 0] # evaluate the determinant
    if np.isclose(det, 0): # the det is zero (can also use ==)
        print('Matrix is non-invertible')
        return
    # set up matrix factor element-wise
    inverse = np.empty((2, 2))
    inverse[0, 0] = A[1, 1]
    inverse[0, 1] = -A[0, 1]
    inverse[1, 0] = -A[1, 0]
    inverse[1, 1] = A[0, 0]
    return inverse/det

inv(B)

Matrix is non-invertible


One application of matrix inverses is solving systems of linear equations. You may have used a matrix method of solving systems like this in a college algebra course.

Let's try the following example: A group of families visited the Science Museum. All of them came to the museum using the bus and left on the train. Tickets for the bus cost \\$4.50 per child and \\$4.80 per adult, and train tickets cost \\$5.25 per child and \\$5.40 per adult. In total, the families spent \\$177.60 on bus tickets and \\$202.80 on train tickets. We can set this up as follows, where $x$ is the number of children and $y$ is the number of adults:

\begin{equation}
4.50x + 4.80y = 177.60 \\
5.25x + 5.40y = 202.80
\end{equation}

We can work backwards from these equations to get a matrix equation. If you're familiar with linear algebra, you can check that the equation above is equivalent to the following:

\begin{equation}
\begin{pmatrix} 4.50 & 4.80 \\ 5.25 & 5.40 \\ \end{pmatrix}
\begin{pmatrix} x \\ y \\ \end{pmatrix} =
\begin{pmatrix} 177.60 \\ 202.80 \\ \end{pmatrix}
\end{equation}

By multiplying both sides of the matrix equation by the inverse, we should get back the matrix of unknowns.

**Your task:** Use your inverse function to solve the problem above. How many children and adults went to the Science Museum?

In [ ]:
prices = np.array([[4.5, 4.8], [5.25, 5.4]]) # lhs matrix of prices
totals = np.array([[177.60], [202.80]]) # rhs matrix of totals
prices_inv = inv(prices) # invert the prices matrix

# "multiply both sides", aka multiply vector by inverse matrix
np.matmul(prices_inv, totals)

array([[16.],
       [22.]])

## Exercise 4: Eigenvalues

An important problem in linear algebra is finding the *eigenvalues* of a matrix, special values intrinsic to matrices which have applications throughout science, especially in physics. Eigenvalues are defined with the eigenvalue equation:

\begin{equation}
Av = \lambda v
\end{equation}

$v$ is an *eigenvector* of $A$, whereas $\lambda$ is an eigenvalue of $A$. The above equation is essentially stating that if I multiply $A$ by one of its eigenvectors, I get back a scalar multiple of that same eigenvector. To solve for eigenvalues, I can multiply the right hand side by the identity matrix (just like how you can multiply a number by 1 without changing its value) and moving all terms to the left hand side to get:

\begin{equation}
Av - \lambda Iv = 0
\end{equation}

Since $v$ can be any vector, we require that the matrix coefficient is the zero matrix:
\begin{equation}
(A - \lambda I) = 0
\end{equation}

This is the *characteristic equation* of $A$, which we can solve by taking the determinant of both sides:
\begin{equation}
det(A - \lambda I) = 0
\end{equation}

For this exercise, we'll stick to 2x2 matrices. This means that the left-hand side will take the form of a quadratic with respect to $\lambda$.

**Your task:** Write a function that takes in a 2x2 matrix and returns its eigenvalues. You won't be able to directly input the above equation into the function like previous exercises; you'll have to figure out how to get the above equation down to a calculable form. (Hint: The left-hand side of the characteristic equation is a polynomial with respect to $\lambda$.)

In [ ]:
# The lhs of the last equation can be expanded for a 2x2 matrix as:
# (A[00] - lamb)(A[11] - lamb) - (A[01])(A[10])
# = lamb**2 - lamb(A[00] + A[11]) + (A[00]A[11] - A[01]A[10])
# This has the format of a quadratic formula, which we've implemented before

def eigen(A):
    a = 1
    b = -A[0, 0] - A[1, 1]
    c = A[0, 0]*A[1, 1] - A[0, 1]*A[1, 0]
    proot = (-b + np.sqrt(b**2 - 4*a*c))/(2*a) # plus root of quadratic formula
    mroot = (-b - np.sqrt(b**2 - 4*a*c))/(2*a) # minus root of quadratic formula
    return (proot, mroot)

(5.372281323269014, -0.3722813232690143)

**Your task:** Test your code with the following examples:

\begin{equation}
\begin{pmatrix}
5 & 4 \\
1 & 2 \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
-5 & 2 \\
-7 & 4 \\
\end{pmatrix}
\end{equation}

\begin{equation}
\begin{pmatrix}
-8 & -3 \\
-5 & 1 \\
\end{pmatrix}
\end{equation}

The function `numpy.linalg.eig()` (https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) returns the eigenvalues and eigenvectors of a matrix input. Use this to compare your answers.

In [ ]:
A = np.array([[5, 4], [1, 2]])
print(eigen(A))
print(np.linalg.eig(A)[0]) # eig() returns (eigenvalues, eigenvectors); we just want to look at the values)

(6.0, 1.0)
[6. 1.]


In [ ]:
B = np.array([[-5, 2], [-7, 4]])
print(eigen(B))
print(np.linalg.eig(B)[0]) # note that the order may be reversed

(2.0, -3.0)
[-3.  2.]


In [ ]:
C = np.array([[-8, -3], [-5, 1]])
print(eigen(C))
print(np.linalg.eig(C)[0])

(2.4371710435189584, -9.437171043518958)
[-9.43717104  2.43717104]
